spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contaspagar
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

jwt:
  secret: mySecretKey
  expirationMs: 3600000
